services:
  api:
    image: scylla23/health-server:latest
    ports:
      - "3000:3000"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}  
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
    restart: unless-stopped
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
    db-data: